### ISSUE TITLE
Fixed scoring of sub-links.

### ISSUE THREAD

**Issue by emma-hubka** [BracciaCJ/2022-CornHacks#52]
Google search "Mozilla"

![single-link](https://user-images.githubusercontent.com/34105895/150664257-67c5947f-2a34-49a9-b372-a29b5ec79ee4.PNG)

**Comment by Bracciata** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/13560664/150668190-24c91a5c-568f-4eeb-899c-0a85e1a5fd57.png">
